-- create "Users" table link to auth.users
create table if not exists public."Users" (
    id uuid not null default auth.uid (),
    role text not null default '' :: text,
    first_name text null default '' :: text,
    last_name text null default '' :: text,
    email text not null,
    constraint AuthorizedUsers_pkey primary key (id)
) tablespace pg_default;

-- create "Students" table
create table if not exists public."Students" (
    id uuid not null,
    first_name text null,
    last_name text null,
    email text not null,
    constraint Students_pkey primary key (id),
    constraint Students_email_key unique (email),
    constraint Students_id_fkey foreign key (id) references "Users" (id) on update cascade on delete cascade
) tablespace pg_default;

-- create "Professors" table
create table if not exists public."Professors" (
    id uuid not null,
    first_name text null,
    last_name text null,
    email text not null,
    constraint Profesors_pkey primary key (id),
    constraint Profesors_email_key unique (email),
    constraint Profesors_id_fkey foreign key (id) references "Users" (id) on update cascade on delete cascade
) tablespace pg_default;

-- create "Templates" table
create table if not exists public."Templates" (
    id bigint generated by default as identity,
    professor_id uuid not null,
    temp_name text not null,
    temp_description text null,
    temp_text text not null,
    constraint Template_pkey primary key (id),
    constraint Templates_professor_id_fkey foreign key (professor_id) references "Professors" (id)
) tablespace pg_default;

-- create "Courses" table
create table if not exists public."Courses" (
    id bigint generated by default as identity,
    prefix text not null,
    code bigint not null,
    name text not null,
    section text null,
    semester text not null,
    year bigint not null,
    constraint Course_pkey primary key (id),
    constraint unique_courses unique (prefix, code, name, section, semester, year)
) tablespace pg_default;

-- create "StudentCourse" join table
create table if not exists public."StudentCourse" (
    student_id uuid not null,
    course_id bigint not null,
    is_grader boolean not null,
    constraint StudentCourse_pkey primary key (student_id, course_id),
    constraint StudentCourse_course_id_fkey foreign key (course_id) references "Courses" (id),
    constraint StudentCourse_student_id_fkey foreign key (student_id) references "Students" (id)
) tablespace pg_default;

-- create "ProfessorCourse" join table
create table if not exists public."ProfessorCourse" (
    professor_id uuid not null,
    course_id bigint not null,
    constraint ProfessorCourse_pkey primary key (professor_id, course_id),
    constraint ProfessorCourse_course_id_fkey foreign key (course_id) references "Courses" (id),
    constraint ProfessorCourse_professor_id_fkey foreign key (professor_id) references "Professors" (id)
) tablespace pg_default;

-- create "Assignments" table
create table if not exists public."Assignments" (
    id bigint generated by default as identity,
    course_id bigint not null,
    assignment_name text not null,
    constraint Assignment_pkey primary key (id),
    constraint Assignments_course_id_assignment_name_key unique (course_id, assignment_name),
    constraint Assignments_course_id_fkey foreign key (course_id) references "Courses" (id)
) tablespace pg_default;

-- create "Appeals" table
create table if not exists public."Appeals" (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    assignment_id bigint not null,
    appeal_text text not null,
    is_open boolean not null,
    grade bigint null,
    constraint Appeal_pkey primary key (id),
    constraint Appeals_assignment_id_fkey foreign key (assignment_id) references "Assignments" (id)
) tablespace pg_default;

-- create "StudentAppeal" join table
create table if not exists public."StudentAppeal" (
    student_id uuid not null,
    appeal_id bigint not null,
    constraint StudentAppeal_pkey primary key (student_id, appeal_id),
    constraint StudentAppeal_appeal_id_fkey foreign key (appeal_id) references "Appeals" (id),
    constraint StudentAppeal_student_id_fkey foreign key (student_id) references "Students" (id)
) tablespace pg_default;

-- create "Messages" table
create table if not exists public."Messages" (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sender_id uuid not null,
    recipient_id uuid not null,
    appeal_id bigint not null,
    message_text text not null,
    from_grader boolean not null,
    constraint Message_pkey primary key (id),
    constraint Messages_appeal_id_fkey foreign key (appeal_id) references "Appeals" (id),
    constraint Messages_recipient_id_fkey foreign key (recipient_id) references "Users" (id),
    constraint Messages_sender_id_fkey foreign key (sender_id) references "Users" (id)
) tablespace pg_default;